"""initial

Revision ID: 461e42307204
Revises: 
Create Date: 2024-02-13 13:44:00.686482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461e42307204'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_from_user_id', sa.Integer(), nullable=False),
    sa.Column('message_from_support_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_requests')
    op.drop_table('blocklist')
    # ### end Alembic commands ###
